version: '3.8'

services:
  billing_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: billing_backend
    environment:
      # Áp dụng y hệt cấu trúc cũ của bạn để gọi file application-prod.properties
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=50MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=50MB
      - DB_USERNAME=${DB_USERNAME:-root}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://171.254.92.12:3306/${DB_NAME:-billing_platform}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
    ports:
      - "8081:8080"
    restart: always

  billing_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://thucuoc.crmkhdncto.id.vn/api
    container_name: billing_frontend
    ports:
      - "8002:80"
    depends_on:
      - billing_backend
    restart: always
